// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackR.DataContext.SQL;

#nullable disable

namespace TrackR.DataContext.SQL.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20230628223625_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackR.Models.SQL.Activity", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("BoardId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            BoardId = 1,
                            CreatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2120),
                            Issue = "Build the data models for SQL database",
                            Title = "Build SQL Data Models",
                            UpdatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2120),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TrackR.Models.SQL.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BoardId");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            BoardId = 1,
                            CreatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2080),
                            Name = "TrackR",
                            UpdatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2090)
                        });
                });

            modelBuilder.Entity("TrackR.Models.SQL.Subtask", b =>
                {
                    b.Property<int>("SubtaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubtaskId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SubtaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("Subtask");

                    b.HasData(
                        new
                        {
                            SubtaskId = 1,
                            CreatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2150),
                            Issue = "Build out the model for boards",
                            TaskId = 1,
                            Title = "Board Model",
                            UpdatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2150)
                        },
                        new
                        {
                            SubtaskId = 2,
                            CreatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2150),
                            Issue = "Build out the model for user",
                            TaskId = 1,
                            Title = "User Model",
                            UpdatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2150)
                        },
                        new
                        {
                            SubtaskId = 3,
                            CreatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2160),
                            Issue = "Build out the activity for boards",
                            TaskId = 1,
                            Title = "Activity Model",
                            UpdatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2170)
                        },
                        new
                        {
                            SubtaskId = 4,
                            CreatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2170),
                            Issue = "Build out the Subtask for user",
                            TaskId = 1,
                            Title = "Subtask Model",
                            UpdatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(2180)
                        });
                });

            modelBuilder.Entity("TrackR.Models.SQL.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(1660),
                            Email = "Joseph.Huntley@outlook.com",
                            FirstName = "Joseph",
                            LastName = "Huntley",
                            Password = "EE644E5589252771C567F22655CB7F73F18284D9BB2E7F3A99BB094E2638AE21863CFBE2E3CD29A2782B03FCAB34C382A4E571897B0D6B708F7058B50DCA7BAE",
                            Salt = new byte[] { 170, 217, 79, 195, 142, 186, 217, 184, 222, 127, 13, 240, 56, 89, 112, 197, 160, 44, 234, 23, 203, 191, 74, 130, 208, 101, 208, 118, 62, 129, 81, 222, 60, 243, 45, 7, 237, 33, 29, 57, 2, 166, 180, 77, 213, 194, 226, 68, 118, 16, 84, 16, 249, 100, 128, 145, 213, 252, 8, 142, 217, 101, 196, 66 },
                            UpdatedDate = new DateTime(2023, 6, 28, 18, 36, 25, 463, DateTimeKind.Local).AddTicks(1740)
                        });
                });

            modelBuilder.Entity("TrackR.Models.SQL.Activity", b =>
                {
                    b.HasOne("TrackR.Models.SQL.Board", "Parent")
                        .WithMany("Tasks")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackR.Models.SQL.User", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TrackR.Models.SQL.Subtask", b =>
                {
                    b.HasOne("TrackR.Models.SQL.Activity", "Parent")
                        .WithMany("Subtasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TrackR.Models.SQL.Activity", b =>
                {
                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("TrackR.Models.SQL.Board", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
